// <auto-generated />
namespace Wed_ShopGaming.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adddblinhkien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddblinhkien));
        
        string IMigrationMetadata.Id
        {
            get { return "202303181006032_add db linhkien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
